# Data Wrangling

Load & transform NBA dataset

Ensure the two datasets are located in folder called data (or update load filepath)

In [20]:
import pandas as pd
import polars as pl
import numpy as np

In [67]:
# Load raw csv data
df_shots = pl.read_csv("data/shotdetail_2024.csv", try_parse_dates=True)
df_cdnnba = pl.read_csv("data/cdnnba_2024.csv", try_parse_dates=True)
df_shots.head(10)

shape: (10, 24)
┌────────────┬──────────┬───────────────┬───────────┬───┬──────────────────┬───────────┬─────┬─────┐
│ GRID_TYPE  ┆ GAME_ID  ┆ GAME_EVENT_ID ┆ PLAYER_ID ┆ … ┆ SHOT_MADE_FLAG   ┆ GAME_DATE ┆ HTM ┆ VTM │
│ ---        ┆ ---      ┆ ---           ┆ ---       ┆   ┆ ---              ┆ ---       ┆ --- ┆ --- │
│ str        ┆ i64      ┆ i64           ┆ i64       ┆   ┆ i64              ┆ i64       ┆ str ┆ str │
╞════════════╪══════════╪═══════════════╪═══════════╪═══╪══════════════════╪═══════════╪═════╪═════╡
│ Shot Chart ┆ 22400001 ┆ 7             ┆ 1642258   ┆ … ┆ 0                ┆ 20241112  ┆ BOS ┆ ATL │
│ Detail     ┆          ┆               ┆           ┆   ┆                  ┆           ┆     ┆     │
│ Shot Chart ┆ 22400001 ┆ 10            ┆ 1630552   ┆ … ┆ 0                ┆ 20241112  ┆ BOS ┆ ATL │
│ Detail     ┆          ┆               ┆           ┆   ┆                  ┆           ┆     ┆     │
│ Shot Chart ┆ 22400001 ┆ 21            ┆ 1630552   ┆ … ┆ 1                ┆ 20241112  ┆ BOS ┆ ATL │
│ Detail     ┆          ┆               ┆           ┆   ┆                  ┆           ┆     ┆     │
│ Shot Chart ┆ 22400001 ┆ 34            ┆ 1630811   ┆ … ┆ 0                ┆ 20241112  ┆ BOS ┆ ATL │
│ Detail     ┆          ┆               ┆           ┆   ┆                  ┆           ┆     ┆     │
│ Shot Chart ┆ 22400001 ┆ 36            ┆ 203991    ┆ … ┆ 1                ┆ 20241112  ┆ BOS ┆ ATL │
│ Detail     ┆          ┆               ┆           ┆   ┆                  ┆           ┆     ┆     │
│ Shot Chart ┆ 22400001 ┆ 39            ┆ 1642258   ┆ … ┆ 1                ┆ 20241112  ┆ BOS ┆ ATL │
│ Detail     ┆          ┆               ┆           ┆   ┆                  ┆           ┆     ┆     │
│ Shot Chart ┆ 22400001 ┆ 46            ┆ 1642258   ┆ … ┆ 0                ┆ 20241112  ┆ BOS ┆ ATL │
│ Detail     ┆          ┆               ┆           ┆   ┆                  ┆           ┆     ┆     │
│ Shot Chart ┆ 22400001 ┆ 48            ┆ 1642258   ┆ … ┆ 0                ┆ 20241112  ┆ BOS ┆ ATL │
│ Detail     ┆          ┆               ┆           ┆   ┆                  ┆           ┆     ┆     │
│ Shot Chart ┆ 22400001 ┆ 50            ┆ 1642258   ┆ … ┆ 0                ┆ 20241112  ┆ BOS ┆ ATL │
│ Detail     ┆          ┆               ┆           ┆   ┆                  ┆           ┆     ┆     │
│ Shot Chart ┆ 22400001 ┆ 52            ┆ 1642258   ┆ … ┆ 0                ┆ 20241112  ┆ BOS ┆ ATL │
│ Detail     ┆          ┆               ┆           ┆   ┆                  ┆           ┆     ┆     │
└────────────┴──────────┴───────────────┴───────────┴───┴──────────────────┴───────────┴─────┴─────┘

In [68]:
df_shots.columns

['GRID_TYPE',
 'GAME_ID',
 'GAME_EVENT_ID',
 'PLAYER_ID',
 'PLAYER_NAME',
 'TEAM_ID',
 'TEAM_NAME',
 'PERIOD',
 'MINUTES_REMAINING',
 'SECONDS_REMAINING',
 'EVENT_TYPE',
 'ACTION_TYPE',
 'SHOT_TYPE',
 'SHOT_ZONE_BASIC',
 'SHOT_ZONE_AREA',
 'SHOT_ZONE_RANGE',
 'SHOT_DISTANCE',
 'LOC_X',
 'LOC_Y',
 'SHOT_ATTEMPTED_FLAG',
 'SHOT_MADE_FLAG',
 'GAME_DATE',
 'HTM',
 'VTM']

In [69]:
df_cdnnba.head(10)

shape: (10, 57)
┌────────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ actionNumb ┆ clock      ┆ timeActual ┆ period ┆ … ┆ foulTechn ┆ foulDrawn ┆ foulDrawn ┆ gameId   │
│ er         ┆ ---        ┆ ---        ┆ ---    ┆   ┆ icalTotal ┆ PlayerNam ┆ PersonId  ┆ ---      │
│ ---        ┆ str        ┆ datetime[μ ┆ i64    ┆   ┆ ---       ┆ e         ┆ ---       ┆ i64      │
│ i64        ┆            ┆ s, UTC]    ┆        ┆   ┆ i64       ┆ ---       ┆ i64       ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ str       ┆           ┆          │
╞════════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2          ┆ PT12M00.00 ┆ 2024-11-13 ┆ 1      ┆ … ┆ null      ┆ null      ┆ null      ┆ 22400001 │
│            ┆ S          ┆ 00:10:24.9 ┆        ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆ 00 UTC     ┆        ┆   ┆           ┆           ┆           ┆          │
│ 4          ┆ PT11M58.00 ┆ 2024-11-13 ┆ 1      ┆ … ┆ null      ┆ null      ┆ null      ┆ 22400001 │
│            ┆ S          ┆ 00:10:26.8 ┆        ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆ 00 UTC     ┆        ┆   ┆           ┆           ┆           ┆          │
│ 7          ┆ PT11M43.00 ┆ 2024-11-13 ┆ 1      ┆ … ┆ null      ┆ null      ┆ null      ┆ 22400001 │
│            ┆ S          ┆ 00:10:40   ┆        ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆ UTC        ┆        ┆   ┆           ┆           ┆           ┆          │
│ 8          ┆ PT11M43.00 ┆ 2024-11-13 ┆ 1      ┆ … ┆ null      ┆ null      ┆ null      ┆ 22400001 │
│            ┆ S          ┆ 00:10:40   ┆        ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆ UTC        ┆        ┆   ┆           ┆           ┆           ┆          │
│ 9          ┆ PT11M42.00 ┆ 2024-11-13 ┆ 1      ┆ … ┆ null      ┆ null      ┆ null      ┆ 22400001 │
│            ┆ S          ┆ 00:10:41   ┆        ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆ UTC        ┆        ┆   ┆           ┆           ┆           ┆          │
│ 10         ┆ PT11M38.00 ┆ 2024-11-13 ┆ 1      ┆ … ┆ null      ┆ null      ┆ null      ┆ 22400001 │
│            ┆ S          ┆ 00:10:46   ┆        ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆ UTC        ┆        ┆   ┆           ┆           ┆           ┆          │
│ 11         ┆ PT11M37.00 ┆ 2024-11-13 ┆ 1      ┆ … ┆ null      ┆ null      ┆ null      ┆ 22400001 │
│            ┆ S          ┆ 00:10:47   ┆        ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆ UTC        ┆        ┆   ┆           ┆           ┆           ┆          │
│ 12         ┆ PT11M24.00 ┆ 2024-11-13 ┆ 1      ┆ … ┆ null      ┆ null      ┆ null      ┆ 22400001 │
│            ┆ S          ┆ 00:11:00.3 ┆        ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆ 00 UTC     ┆        ┆   ┆           ┆           ┆           ┆          │
│ 13         ┆ PT11M22.00 ┆ 2024-11-13 ┆ 1      ┆ … ┆ null      ┆ null      ┆ null      ┆ 22400001 │
│            ┆ S          ┆ 00:11:02.3 ┆        ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆ 00 UTC     ┆        ┆   ┆           ┆           ┆           ┆          │
│ 14         ┆ PT11M17.00 ┆ 2024-11-13 ┆ 1      ┆ … ┆ null      ┆ null      ┆ null      ┆ 22400001 │
│            ┆ S          ┆ 00:11:08.9 ┆        ┆   ┆           ┆           ┆           ┆          │
│            ┆            ┆ 00 UTC     ┆        ┆   ┆           ┆           ┆           ┆          │
└────────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [70]:
df_cdnnba.columns

['actionNumber',
 'clock',
 'timeActual',
 'period',
 'periodType',
 'actionType',
 'subType',
 'qualifiers',
 'personId',
 'x',
 'y',
 'possession',
 'scoreHome',
 'scoreAway',
 'edited',
 'orderNumber',
 'isTargetScoreLastPeriod',
 'xLegacy',
 'yLegacy',
 'isFieldGoal',
 'side',
 'description',
 'personIdsFilter',
 'teamId',
 'teamTricode',
 'descriptor',
 'jumpBallRecoveredName',
 'jumpBallRecoverdPersonId',
 'playerName',
 'playerNameI',
 'jumpBallWonPlayerName',
 'jumpBallWonPersonId',
 'jumpBallLostPlayerName',
 'jumpBallLostPersonId',
 'area',
 'areaDetail',
 'shotDistance',
 'shotResult',
 'blockPlayerName',
 'blockPersonId',
 'shotActionNumber',
 'reboundTotal',
 'reboundDefensiveTotal',
 'reboundOffensiveTotal',
 'officialId',
 'turnoverTotal',
 'stealPlayerName',
 'stealPersonId',
 'pointsTotal',
 'assistPlayerNameInitial',
 'assistPersonId',
 'assistTotal',
 'foulPersonalTotal',
 'foulTechnicalTotal',
 'foulDrawnPlayerName',
 'foulDrawnPersonId',
 'gameId']

In [ ]:
# Merge two dataframes
df_merged = df_shots.join(df_cdnnba, how='left', left_on=['GAME_ID', 'GAME_EVENT_ID'], right_on=['gameId', 'actionNumber'])
df_merged.head(10)

shape: (10, 79)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ GRID_TYPE ┆ GAME_ID  ┆ GAME_EVEN ┆ PLAYER_ID ┆ … ┆ foulPerso ┆ foulTechn ┆ foulDrawn ┆ foulDrawn │
│ ---       ┆ ---      ┆ T_ID      ┆ ---       ┆   ┆ nalTotal  ┆ icalTotal ┆ PlayerNam ┆ PersonId  │
│ str       ┆ i64      ┆ ---       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ e         ┆ ---       │
│           ┆          ┆ i64       ┆           ┆   ┆ i64       ┆ i64       ┆ ---       ┆ i64       │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ str       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Shot      ┆ 22400001 ┆ 7         ┆ 1642258   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 10        ┆ 1630552   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 21        ┆ 1630552   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 34        ┆ 1630811   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 36        ┆ 203991    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 39        ┆ 1642258   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 46        ┆ 1642258   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 48        ┆ 1642258   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 50        ┆ 1642258   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 52        ┆ 1642258   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ Chart     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
# Requires conversion to polars dataframe
# Check merge correct

df_test = df_merged['TEAM_ID'] != df_merged['teamId']
df_test2 = df_merged['PLAYER_ID'] != df_merged['personId'] 

# Display Team ID discrepancies
df_merged[['TEAM_ID', 'teamId']][df_test]

ValueError: expected 2 values when selecting columns by boolean mask, got 219527

In [ ]:
# Requires conversion to polars dataframe

# Display Player ID discrepancies
df_merged[['PLAYER_ID', 'personId']][df_test2]

        PLAYER_ID   personId
27517     1641878  1641733.0
44436     1630702        NaN
53316      203999        NaN
107477    1642377  1630590.0
110718    1629639  1631107.0
131012    1629638  1630183.0
131013    1630183  1629638.0
133262    1642274  1629750.0
207388     203903  1631117.0
212843    1629673        NaN

In [ ]:
# Convert data types
df_merged = df_merged.with_columns(
    pl.col('GAME_DATE').cast(pl.String).str.to_datetime(format="%Y%m%d").alias('game_date'),
    pl.duration(minutes=pl.col('MINUTES_REMAINING'), seconds=pl.col('SECONDS_REMAINING')).alias('time_remaining'),
    (pl.col('scoreHome') - pl.col('scoreAway')).alias('score_margin')
)

# Convert to based on player taking actions perspective
df_merged = df_merged.with_columns(
    pl.when(pl.col('teamTricode') == pl.col('HTM')).then(pl.col('score_margin')).otherwise(pl.col('score_margin')*-1).alias('margin_action')
)

In [73]:
df_merged.columns

['GRID_TYPE',
 'GAME_ID',
 'GAME_EVENT_ID',
 'PLAYER_ID',
 'PLAYER_NAME',
 'TEAM_ID',
 'TEAM_NAME',
 'PERIOD',
 'MINUTES_REMAINING',
 'SECONDS_REMAINING',
 'EVENT_TYPE',
 'ACTION_TYPE',
 'SHOT_TYPE',
 'SHOT_ZONE_BASIC',
 'SHOT_ZONE_AREA',
 'SHOT_ZONE_RANGE',
 'SHOT_DISTANCE',
 'LOC_X',
 'LOC_Y',
 'SHOT_ATTEMPTED_FLAG',
 'SHOT_MADE_FLAG',
 'GAME_DATE',
 'HTM',
 'VTM',
 'clock',
 'timeActual',
 'period',
 'periodType',
 'actionType',
 'subType',
 'qualifiers',
 'personId',
 'x',
 'y',
 'possession',
 'scoreHome',
 'scoreAway',
 'edited',
 'orderNumber',
 'isTargetScoreLastPeriod',
 'xLegacy',
 'yLegacy',
 'isFieldGoal',
 'side',
 'description',
 'personIdsFilter',
 'teamId',
 'teamTricode',
 'descriptor',
 'jumpBallRecoveredName',
 'jumpBallRecoverdPersonId',
 'playerName',
 'playerNameI',
 'jumpBallWonPlayerName',
 'jumpBallWonPersonId',
 'jumpBallLostPlayerName',
 'jumpBallLostPersonId',
 'area',
 'areaDetail',
 'shotDistance',
 'shotResult',
 'blockPlayerName',
 'blockPersonId',
 'shotActionNumber',
 'reboundTotal',
 'reboundDefensiveTotal',
 'reboundOffensiveTotal',
 'officialId',
 'turnoverTotal',
 'stealPlayerName',
 'stealPersonId',
 'pointsTotal',
 'assistPlayerNameInitial',
 'assistPersonId',
 'assistTotal',
 'foulPersonalTotal',
 'foulTechnicalTotal',
 'foulDrawnPlayerName',
 'foulDrawnPersonId',
 'game_date',
 'time_remaining',
 'score_margin',
 'margin_action']

In [91]:
# Confirm no mismatching data between event types & shot flags
made_shots_mismatch = df_merged.filter(
    (pl.col('EVENT_TYPE') =='Made Shot') & (pl.col('SHOT_ATTEMPTED_FLAG')!=1) & (pl.col('SHOT_MADE_FLAG')!=1)
)


missed_shots_mismatch = df_merged.filter(
    (pl.col('EVENT_TYPE') =='Missed Shot') & (pl.col('SHOT_ATTEMPTED_FLAG')!=1) & (pl.col('SHOT_MADE_FLAG')!=0)
)

print(made_shots_mismatch)
print(missed_shots_mismatch)

shape: (0, 83)
┌───────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ GRID_TYPE ┆ GAME_ID ┆ GAME_EVENT ┆ PLAYER_ID ┆ … ┆ game_date ┆ time_rema ┆ score_mar ┆ margin_ac │
│ ---       ┆ ---     ┆ _ID        ┆ ---       ┆   ┆ ---       ┆ ining     ┆ gin       ┆ tion      │
│ str       ┆ i64     ┆ ---        ┆ i64       ┆   ┆ datetime[ ┆ ---       ┆ ---       ┆ ---       │
│           ┆         ┆ i64        ┆           ┆   ┆ μs]       ┆ duration[ ┆ i64       ┆ i64       │
│           ┆         ┆            ┆           ┆   ┆           ┆ μs]       ┆           ┆           │
╞═══════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
└───────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
shape: (0, 83)
┌───────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ GRID_TYPE ┆ GAME_ID ┆ GAME_EVENT ┆ PLAYER_ID ┆ … ┆ game_date ┆ time_rema ┆ score_mar ┆ margin_ac │
│ ---       ┆ ---     ┆ _ID        ┆ ---       ┆   ┆ ---       ┆ ining     ┆ gin       ┆ tion      │
│ str       ┆ i64     ┆ ---        ┆ i64       ┆   ┆ datetime[ ┆ ---       ┆ ---       ┆ ---       │
│           ┆         ┆ i64        ┆           ┆   ┆ μs]       ┆ duration[ ┆ i64       ┆ i64       │
│           ┆         ┆            ┆           ┆   ┆           ┆ μs]       ┆           ┆           │
╞═══════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
└───────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [92]:
# Drop redundant columns
df2 = df_merged.drop(['period', 'personId', 'actionType', 'GAME_DATE', 'SHOT_DISTANCE'])

# Drop columns deemed not required
df2 = df2.drop([
    'EVENT_TYPE',
    'MINUTES_REMAINING',
    'SECONDS_REMAINING',
    'foulPersonalTotal',
    'foulTechnicalTotal',
    'foulDrawnPlayerName',
    'foulDrawnPersonId',
    'area',
    'areaDetail',
    'shotResult',
    'officialId',
    'turnoverTotal',
    'stealPlayerName',
    'stealPersonId',
    'reboundTotal',
    'reboundDefensiveTotal',
    'reboundOffensiveTotal',
    'blockPlayerName',
    'blockPersonId',
    'jumpBallLostPlayerName',
    'jumpBallLostPersonId',
    'jumpBallWonPlayerName',
    'jumpBallWonPersonId', 
    'jumpBallRecoveredName',    
    'jumpBallRecoverdPersonId',
    'shotActionNumber'
])
df2

shape: (219_527, 52)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ GRID_TYPE ┆ GAME_ID  ┆ GAME_EVEN ┆ PLAYER_ID ┆ … ┆ game_date ┆ time_rema ┆ score_mar ┆ margin_ac │
│ ---       ┆ ---      ┆ T_ID      ┆ ---       ┆   ┆ ---       ┆ ining     ┆ gin       ┆ tion      │
│ str       ┆ i64      ┆ ---       ┆ i64       ┆   ┆ datetime[ ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ i64       ┆           ┆   ┆ μs]       ┆ duration[ ┆ i64       ┆ i64       │
│           ┆          ┆           ┆           ┆   ┆           ┆ μs]       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Shot      ┆ 22400001 ┆ 7         ┆ 1642258   ┆ … ┆ 2024-11-1 ┆ 11m 43s   ┆ 0         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆ 2         ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 10        ┆ 1630552   ┆ … ┆ 2024-11-1 ┆ 11m 38s   ┆ 0         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆ 2         ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 21        ┆ 1630552   ┆ … ┆ 2024-11-1 ┆ 10m 50s   ┆ -3        ┆ 3         │
│ Chart     ┆          ┆           ┆           ┆   ┆ 2         ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 34        ┆ 1630811   ┆ … ┆ 2024-11-1 ┆ 9m 47s    ┆ 0         ┆ 0         │
│ Chart     ┆          ┆           ┆           ┆   ┆ 2         ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆           │
│ Shot      ┆ 22400001 ┆ 36        ┆ 203991    ┆ … ┆ 2024-11-1 ┆ 9m 44s    ┆ -2        ┆ 2         │
│ Chart     ┆          ┆           ┆           ┆   ┆ 2         ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Shot      ┆ 22401217 ┆ 643       ┆ 1629673   ┆ … ┆ 2024-12-1 ┆ 3m 14s    ┆ -15       ┆ -15       │
│ Chart     ┆          ┆           ┆           ┆   ┆ 5         ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆           │
│ Shot      ┆ 22401217 ┆ 646       ┆ 1629673   ┆ … ┆ 2024-12-1 ┆ 2m 53s    ┆ -18       ┆ -18       │
│ Chart     ┆          ┆           ┆           ┆   ┆ 5         ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆           │
│ Shot      ┆ 22401217 ┆ 661       ┆ 1642259   ┆ … ┆ 2024-12-1 ┆ 2m 11s    ┆ -18       ┆ -18       │
│ Chart     ┆          ┆           ┆           ┆   ┆ 5         ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆           │
│ Shot      ┆ 22401217 ┆ 668       ┆ 1630551   ┆ … ┆ 2024-12-1 ┆ 1m 45s    ┆ -16       ┆ -16       │
│ Chart     ┆          ┆           ┆           ┆   ┆ 5         ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆           │
│ Shot      ┆ 22401217 ┆ 672       ┆ 1629673   ┆ … ┆ 2024-12-1 ┆ 1m 20s    ┆ -14       ┆ -14       │
│ Chart     ┆          ┆           ┆           ┆   ┆ 5         ┆           ┆           ┆           │
│ Detail    ┆          ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [88]:
df2.describe()

shape: (9, 56)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ GRID_TYPE ┆ GAME_ID   ┆ GAME_EVEN ┆ … ┆ game_date ┆ time_rema ┆ score_mar ┆ margin_a │
│ ---       ┆ ---       ┆ ---       ┆ T_ID      ┆   ┆ ---       ┆ ining     ┆ gin       ┆ ction    │
│ str       ┆ str       ┆ f64       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆ str       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 219527    ┆ 219527.0  ┆ 219527.0  ┆ … ┆ 219527    ┆ 219527    ┆ 219524.0  ┆ 219524.0 │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 3.0       ┆ 3.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2.2401e7  ┆ 330.56749 ┆ … ┆ 2025-01-1 ┆ 0:05:51.9 ┆ 0.873326  ┆ 0.448179 │
│           ┆           ┆           ┆ 3         ┆   ┆ 7 23:13:3 ┆ 70044     ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 1.532066  ┆           ┆           ┆          │
│ std       ┆ null      ┆ 354.58010 ┆ 199.05874 ┆ … ┆ null      ┆ null      ┆ 11.84318  ┆ 11.86687 │
│           ┆           ┆ 3         ┆ 2         ┆   ┆           ┆           ┆           ┆ 6        │
│ min       ┆ Shot      ┆ 2.2400001 ┆ 4.0       ┆ … ┆ 2024-10-2 ┆ 0:00:00   ┆ -59.0     ┆ -61.0    │
│           ┆ Chart     ┆ e7        ┆           ┆   ┆ 2         ┆           ┆           ┆          │
│           ┆ Detail    ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2.240031e ┆ 157.0     ┆ … ┆ 2024-12-0 ┆ 0:02:52   ┆ -6.0      ┆ -6.0     │
│           ┆           ┆ 7         ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2.2400618 ┆ 329.0     ┆ … ┆ 2025-01-1 ┆ 0:05:53   ┆ 1.0       ┆ 0.0      │
│           ┆           ┆ e7        ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2.2400923 ┆ 498.0     ┆ … ┆ 2025-03-0 ┆ 0:08:53   ┆ 8.0       ┆ 7.0      │
│           ┆           ┆ e7        ┆           ┆   ┆ 5         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ max       ┆ Shot      ┆ 2.240123e ┆ 851.0     ┆ … ┆ 2025-04-1 ┆ 0:12:00   ┆ 64.0      ┆ 64.0     │
│           ┆ Chart     ┆ 7         ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│           ┆ Detail    ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘